services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    restart: unless-stopped
    container_name: horizon-frontend
    environment:
      - NODE_ENV=production
